In [7]:
#第七章 数据清洗和准备
#pandas使用浮点数NaN(Not a Number)表示缺失数据
import pandas as pd
import numpy as np
string_data = pd.Series(['aasdsd','article',np.nan,'avocado'])
string_data

0     aasdsd
1    article
2        NaN
3    avocado
dtype: object

In [8]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
#pandas中采用R语言的惯用法，即将缺失值表示为NA，即：not available
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
#滤除缺失数据:dropna返回一个仅含非空数据和索引值的Series：
string_data.dropna()

1    article
3    avocado
dtype: object

In [12]:
#等价于
string_data[string_data.notnull()]

1    article
3    avocado
dtype: object

In [15]:
#但是对于DataFramed对象，可能希望丢弃全NA或者NA的行和列
from numpy import nan as NA
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [17]:
#假如参数how="all"将只丢弃权威全为NA的那些行
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
#假如参数axis = 1即可删除列
data.dropna(axis = 1,how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.355106       NaN       NaN
1 -0.213658       NaN       NaN
2 -0.747295       NaN  0.544063
3 -0.847963       NaN  0.653770
4 -0.431169  0.559675 -0.113383
5  0.161956 -0.285685  2.316672
6  1.504460 -1.057949  1.800011

In [22]:
#留下一部分观测数据
df.dropna(thresh = 2)

0         1         2
2 -0.747295       NaN  0.544063
3 -0.847963       NaN  0.653770
4 -0.431169  0.559675 -0.113383
5  0.161956 -0.285685  2.316672
6  1.504460 -1.057949  1.800011

In [25]:
#填充缺失数据：fillna参数
df.fillna(0)

0         1         2
0 -0.355106  0.000000  0.000000
1 -0.213658  0.000000  0.000000
2 -0.747295  0.000000  0.544063
3 -0.847963  0.000000  0.653770
4 -0.431169  0.559675 -0.113383
5  0.161956 -0.285685  2.316672
6  1.504460 -1.057949  1.800011

In [26]:
#通过一个dict调用fillna，可以实现对不同的列填充不同的值
df.fillna({1:0.5,2:0})

0         1         2
0 -0.355106  0.500000  0.000000
1 -0.213658  0.500000  0.000000
2 -0.747295  0.500000  0.544063
3 -0.847963  0.500000  0.653770
4 -0.431169  0.559675 -0.113383
5  0.161956 -0.285685  2.316672
6  1.504460 -1.057949  1.800011

In [29]:
#对现有对象进行就地修改
_ = df.fillna(0,inplace=True)
df

0         1         2
0 -0.355106  0.000000  0.000000
1 -0.213658  0.000000  0.000000
2 -0.747295  0.000000  0.544063
3 -0.847963  0.000000  0.653770
4 -0.431169  0.559675 -0.113383
5  0.161956 -0.285685  2.316672
6  1.504460 -1.057949  1.800011

In [32]:
#对reindexing有效的那些插值方法也可用于fillna：
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0  0.137548  0.012670  0.960945
1  0.151992  1.109279 -0.354160
2  0.236482       NaN  0.675752
3  1.334471       NaN -0.364409
4  1.489175       NaN       NaN
5 -0.596789       NaN       NaN

In [33]:
df.fillna(method='ffill')

0         1         2
0  0.137548  0.012670  0.960945
1  0.151992  1.109279 -0.354160
2  0.236482  1.109279  0.675752
3  1.334471  1.109279 -0.364409
4  1.489175  1.109279 -0.364409
5 -0.596789  1.109279 -0.364409

In [34]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.137548  0.012670  0.960945
1  0.151992  1.109279 -0.354160
2  0.236482  1.109279  0.675752
3  1.334471  1.109279 -0.364409
4  1.489175       NaN -0.364409
5 -0.596789       NaN -0.364409

In [35]:
data = pd.Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [37]:
#数据转换
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,2,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   2
5  two   4
6  two   4

In [38]:
#DataFrame的duplicated方法返回一个布尔型Series，表示各行是否是重复行（前面出现过的行）
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [39]:
#重复行会被删除
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
5  two   4

In [41]:
#指定列进行重复项判断
data['V1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  V1
0  one   1   0
1  two   1   1

In [42]:
#duplicated和drop_duplicates默认会保留的是第一个出现的值组合，传入keep='last'则保留最后一个
data.drop_duplicates(['k1','k2'],keep = 'last')

k1  k2  V1
0  one   1   0
1  two   1   1
3  two   3   3
4  one   2   4
6  two   4   6

In [52]:
#利用函数或映射进行数据转换
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','novalox'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8      novalox     6.0

In [64]:
meat_to_animal = {'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'novalox': 'salmon'}
#添加一列为肉类食物的动物来源，Series的map方法可以接受一个函数或含有映射关系的字典型对象
#但有些肉类首字母大写，需要转换为小写：
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8        novalox
Name: food, dtype: object

In [65]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8      novalox     6.0  salmon

In [66]:
#可以使用一个能够完成全部这些工作的函数：
data['food'].map(lambda x: meat_to_animal[x.lower()])
#使用map是一种实现元素级转换以及其他数据清理工作的便捷方式

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [67]:
#替换值
data = pd.Series([1.,-999,2.,-999,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [68]:
#-999可能表示缺失数据的标记值
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [73]:
#一次性替换多个值,可以传入一个由替换值组成的列表以及一个替换值：
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [74]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [75]:
#传入的参数也可以是字典
data.replace({-999:np.nan,-1000:0})
#data.replace方法与data.str.replace不同，后者做的是字符串的元素级替换。

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [77]:
#重命名轴索引
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio', 'Colorado', 'New York'], columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [79]:
#轴索引也有一个map方法：
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [81]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [83]:
#创建数据集的转换版：rename
data.rename(index = str.title,columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [86]:
#rename结合dict对象实现对部分轴标签的更新
data.rename(index = {'OHIO':'INDIANA'},columns = {'three':'peekboo'})

one  two  peekboo  four
INDIANA    0    1        2     3
COLO       4    5        6     7
NEW        8    9       10    11

In [87]:
#rename可以实现复制DataFrame并对其索引和列标签进行赋值；如果希望就地修改某个数据集，传入inplace = True即可
data.rename(index = {'OHIO':'INDIANA'},inplace = True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [88]:
#离散化和面元划分
#为了便于分析，连续数据常常被离散化或拆分为“面元（bin）”，假设有一组人员数据，将它们划分为不同的年龄组：
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
#划分bin，使用pandas的cut函数：
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [89]:
#pandas返回的是一个特殊的Categorical对象以及一个codes属性中的年龄数据的标签
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [90]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [91]:
#pd.value_counts(cats)是pandas.cut结果的面元计算
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [92]:
#区间的开端和闭端可以通过参数“right=”修改：
pd.cut(ages,[18,26,36,61,100],right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [93]:
#可以通过传递一个列表或数组到labels，设置自己的面元名称：
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [95]:
data = np.random.rand(20)
#如果向cut传入的是bin的数量而不是确切的bin边界，如：4，则会根据数据的最大值和最小值计算等长面元。
pd.cut(data,4,precision = 2)  #限定小数只有两位

[(0.77, 1.0], (0.55, 0.77], (0.33, 0.55], (0.55, 0.77], (0.55, 0.77], ..., (0.33, 0.55], (0.77, 1.0], (0.55, 0.77], (0.55, 0.77], (0.77, 1.0]]
Length: 20
Categories (4, interval[float64]): [(0.1, 0.33] < (0.33, 0.55] < (0.55, 0.77] < (0.77, 1.0]]

In [96]:
data

array([0.84850554, 0.7091941 , 0.49632663, 0.67483566, 0.71617395,
       0.84676386, 0.5814627 , 0.91059745, 0.2638263 , 0.48190161,
       0.97773845, 0.10546902, 0.51476221, 0.85506013, 0.99723835,
       0.44768438, 0.86023226, 0.55185358, 0.59074204, 0.8052783 ])

In [97]:
#qcut使用样本分位数，可以使bin含有相同数量的数据点
data = np.random.randn(1000)   #Normally distribution
cats = pd.qcut(data,4)   #cut into quartiles
cats

[(-0.628, 0.0147], (-2.751, -0.628], (0.0147, 0.696], (0.0147, 0.696], (0.696, 2.952], ..., (-2.751, -0.628], (-0.628, 0.0147], (-0.628, 0.0147], (0.0147, 0.696], (-2.751, -0.628]]
Length: 1000
Categories (4, interval[float64]): [(-2.751, -0.628] < (-0.628, 0.0147] < (0.0147, 0.696] < (0.696, 2.952]]

In [99]:
pd.value_counts(cats)

(0.696, 2.952]      250
(0.0147, 0.696]     250
(-0.628, 0.0147]    250
(-2.751, -0.628]    250
dtype: int64

In [100]:
#与cut类似，可以传递自定义的分位数(0到1之间的数值，包含端点)
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-1.202, 0.0147], (-1.202, 0.0147], (0.0147, 1.315], (0.0147, 1.315], (1.315, 2.952], ..., (-2.751, -1.202], (-1.202, 0.0147], (-1.202, 0.0147], (0.0147, 1.315], (-1.202, 0.0147]]
Length: 1000
Categories (4, interval[float64]): [(-2.751, -1.202] < (-1.202, 0.0147] < (0.0147, 1.315] < (1.315, 2.952]]

In [105]:
#检测和过滤异常值
#过滤或变换异常值（outlier）在很大程度上就是运用数组运算,如下显示一个正态分布数据的DataFrame：
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.013204    -0.009605    -0.046044    -0.050921
std       0.986760     1.005902     0.980915     1.023978
min      -3.364892    -3.233882    -3.876624    -3.637772
25%      -0.686986    -0.672570    -0.722190    -0.750125
50%      -0.022095    -0.042894    -0.041271    -0.047897
75%       0.651911     0.635895     0.628815     0.650864
max       3.148412     3.185140     2.939278     3.569306

In [107]:
#某一列中绝对值超过3的值
col = data[2]
col[np.abs(col) > 3]

760   -3.876624
Name: 2, dtype: float64

In [108]:
#挑选出全部含有“超过3或-3的值”的行，可在布尔型DataFrame中使用any方法：
data[(np.abs(data) > 3).any(1)]

0         1         2         3
105  0.225788  1.553364 -0.601418 -3.104930
236 -0.053079 -1.211109 -0.125105  3.073675
308  0.330987  1.146006  0.735316 -3.637772
398  1.884900  0.352739 -0.755880 -3.003384
423  0.761840 -0.782319 -1.319777  3.023306
470  0.897470  3.185140  0.302231 -0.312564
556  0.018572 -1.301610  0.669126 -3.277414
620  3.148412 -0.312366  0.765233  1.376548
697 -3.331340  0.615910  0.825133  1.644416
760  1.800285 -0.557524 -3.876624 -1.112480
922 -1.790716  0.328647 -2.825795  3.569306
923  0.682810 -3.233882 -0.238135 -0.410075
943 -3.364892  0.166898 -1.013232 -0.091737

In [121]:
#对值进行设置；限制在区间-3到3以内；np.sign() 函数是根据传入数据的正负号 来得到+1 ,0或 -1，返回一个新的data
data[np.abs(data)>3] = np.sign(data)*3
data.describe()
data[(np.abs(data) == 3).any(1)]

0         1         2         3
105  0.225788  1.553364 -0.601418 -3.000000
236 -0.053079 -1.211109 -0.125105  3.000000
308  0.330987  1.146006  0.735316 -3.000000
398  1.884900  0.352739 -0.755880 -3.000000
423  0.761840 -0.782319 -1.319777  3.000000
470  0.897470  3.000000  0.302231 -0.312564
556  0.018572 -1.301610  0.669126 -3.000000
620  3.000000 -0.312366  0.765233  1.376548
697 -3.000000  0.615910  0.825133  1.644416
760  1.800285 -0.557524 -3.000000 -1.112480
922 -1.790716  0.328647 -2.825795  3.000000
923  0.682810 -3.000000 -0.238135 -0.410075
943 -3.000000  0.166898 -1.013232 -0.091737

In [122]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [132]:
ll = np.sign(data).head()
ll

0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [140]:
#排列和随机采样
#利用numpy.random.permutation函数可以轻松实现对Series或DataFrame的列的排列工作（permuting，随机重排序）
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)
sampler

array([3, 1, 2, 0, 4])

In [142]:
#基于iloc的索引操作或take函数中使用该数组了
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [146]:
#不用替换的方式选取随机子集，可以在Series和DataFrame上使用sample方法：
df.sample(n = 3) #n指定采样的个数

0   1  2   3
0   0   1  2   3
3  12  13  4  15
1   4   5  6   7

In [148]:
#用替换的方式产生样本，可以使用replace = True到sample：
draws = df.sample(n = 10,replace = True)
draws

0   1   2   3
2   8   9  10  11
4  16  17  18  19
4  16  17  18  19
4  16  17  18  19
4  16  17  18  19
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13   4  15
2   8   9  10  11

In [151]:
#计算指标/哑变量
#另一种常用于统计建模或机器学习的转换方式是：将分类变量（categorical variable）转换为“哑变量”或“指标矩阵”
#统计某一列中的值在某一行中是否出现（k个不同则会生成k列），相同的为1，不同的为0
df = pd.DataFrame({'key':['b','b','a','c','d'],'data1':range(5)})
pd.get_dummies(df['key'])

a  b  c  d
0  0  1  0  0
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  0  0  0  1

In [153]:
#DataFrame的列加上一个前缀，以便能跟其他数据进行合并，get_dummies的prefix参数可以实现该功能：
dummies = pd.get_dummies(df['key'],prefix = 'key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c  key_d
0      0      0      1      0      0
1      1      0      1      0      0
2      2      1      0      0      0
3      3      0      0      1      0
4      4      0      0      0      1

In [4]:
#如果DataFrame中的某行同属于多个分类，则：
mnames = ['movie_id','title','genres']
movies = pd.read_csv('datasets/movielens/movies.dat',sep = '::',header = None,names = mnames)
movies[:10]

E:\Anaconda\Setup\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [5]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [7]:
#构建指标DataFrame的方法之一是从一个全零DataFrame开始：
import numpy as np
import pandas as pd
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix,columns = genres)
#迭代每一步电影，并将dummies各行的条目设为1，使用dummies.columns来计算每个类型的列索引：
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [8]:
gen

"Animation|Children's|Comedy"

In [9]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [11]:
#根据索引，使用.iloc设定值
for i ,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1
#再将其与movies合并起来
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]
#对于很大的数据，这种处理方式过慢，最好写入Numpy数组，然后包装到DataFrame中

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [12]:
#结合get_dummies和诸如cut之类的离散化函数：
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [13]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [14]:
#7.3.字符串操作
#字符串对象方法:拆分称数段
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [15]:
#split常常与strip一起使用，以去除空白符（包括换行符）：
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [16]:
#利用加法，可以将这些字符以双冒号分隔符的形式连接起来：
first,second,third = pieces
first+'::'+second+'::'+third

'a::b::guido'

In [17]:
#使用join方法
'::'.join(pieces)

'a::b::guido'

In [20]:
#查找，否为-1
val.find(':')

-1

In [21]:
#查找，index返回异常
val.index(':')

ValueError: substring not found

In [22]:
val.count(',')

2

In [23]:
#替换，也常用于删除
val.replace(',','::')

'a::b:: guido'

In [24]:
val.replace(',','')

'ab guido'

In [25]:
#正则表达式模块的函数分为三大类：模式匹配、替换以及拆分
import re
text = 'foo    bar\t baz   \tqux'
re.split('\s+',text)
#正则表达式先被编译，然后再在text上调用solit方法

['foo', 'bar', 'baz', 'qux']

In [26]:
#可以使用re.compile先编译regex以得到一个可重用的regex对象
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [27]:
#得到匹配regex的所有模式，可使用findall方法：
regex.findall(text)

['    ', '\t ', '   \t']

In [30]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern,flags = re.IGNORECASE)
#使用findall查找方法
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [32]:
#使用search方法查找，只返回文本中第一个电子邮件地址:匹配项只会告诉我们模式在原字符串中的起始和结束位置：
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [34]:
text[m.start():m.end()]

'dave@google.com'

In [35]:
m.start():m.end()

SyntaxError: illegal target for annotation (<ipython-input-35-5d4971b6eb22>, line 1)

In [37]:
#regex.match则返回None，因为其只匹配出现在字符串开头的模式：
print(regex.match(text))

None


In [38]:
#sub方法可以将匹配到的模式替换为指定字符串，并返回得到新字符串：
print(regex.sub('READCTED',text))

Dave READCTED
Steve READCTED
Rob READCTED
Ryan READCTED



In [76]:
#匹配到而且将3个部分拆分：用户名，域名，域后缀；只需将待分段的模式各部分用圆括号抱起来
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern,flags = re.IGNORECASE)
m = regex.match("dkddk@hhafk.io")
m.groups()

('dkddk', 'hhafk', 'io')

In [79]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern,flags = re.IGNORECASE)
#使用findall功能会返回一个元组列表
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [80]:
#sub还能通过诸如\1、\2之类的特殊符号访问各匹配项中的分组；\1对应第一个匹配的组，\2对应第二个匹配的组
print(regex.sub(r'Username:\1,Domain:\2,Suffix:\3',text))

Dave Username:dave,Domain:google,Suffix:com
Steve Username:steve,Domain:gmail,Suffix:com
Rob Username:rob,Domain:gmail,Suffix:com
Ryan Username:ryan,Domain:yahoo,Suffix:com



In [81]:
#pandas的矢量化字符串函数：含有字符串的列有时含有缺失数据：
data = {'Dave': 'dave@google.com', 'Steve':'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [83]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [85]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [86]:
#通过data.map,所有字符串和正则表达式方法都能被应用于(传入lambda表达式或者其他函数)各个值，但如果NA（null）存在就会报错
#Series含有跳过NA值得面向数组方法，进行字符串操作，str属性：str.contains检查各个电子邮件地址是否含有“gmail”

In [87]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [88]:
#也可以用regex，还可以加上任意re选项（如IGNORECASE）
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [90]:
data.str.findall(pattern,flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [91]:
#有两个方法可实现矢量化得元素获取操作：要么使用str.get,要么在str属性上使用索引：
matches = data.str.match(pattern,flags = re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [92]:
#要访问嵌入列表中的元素，我们可以传递索引到这两个函数中：
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [93]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [94]:
#可以利用这种方法对字符串进行截取：
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object