In [1]:
#pandas入门
import pandas as pd
from pandas import Series,DataFrame
#Series是一种类似于一维数组的对象，其由一组数据（各种Numpy数据类型）以及一组与之相关的数据标签（即索引）组成
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [2]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
#可以对各个数据点进行标记的索引：
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2['a']

-5

In [7]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [8]:
obj2[obj2 >0]

d    4
b    7
c    3
dtype: int64

In [12]:
#直接通过dict来创建Series：
sdata = {'ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
#如果只传入一个dict，则结果Series中的索引就是原字典的键（有序排列）
states = ['California','ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4
#在sdata中的California所对应的值找不到，故而是NaN：（not a number）；表示为缺失值。

California        NaN
ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
#pandas的isnull和notnull函数可用于检测缺失数据：
pd.isnull(obj4)

California     True
ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
Series对象本身及其索引都有一个name属性
obj4.name ='population'
obj4.index.name = 'state'
obj4

state
California        NaN
ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [19]:
#DataFrame：表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）,
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002,2003],'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [20]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [21]:
#指定顺序进行排列：
pd.DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [22]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],index = ['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [23]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [24]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [26]:
#行也可以通过位置或名称的方式进行获取，比如用loc属性：
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [27]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [29]:
import numpy as np
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [30]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [31]:
#为不存在的列赋值会创建出一个新列，关键字del用于删除列。
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [32]:
#删除这一列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [34]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [36]:
#嵌套字典
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
#如果嵌套字典传给DataFrame，pandas就会被解释为：外层字典的键作为列，内层键则作为行索引
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [37]:
#转置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [38]:
#内层字典的键会被合并、排序以形成最终的索引
pd.DataFrame(pop,index = [2001,2002,2003])

AttributeError: 'list' object has no attribute 'astype'

In [41]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [42]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [43]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [44]:
#索引对象
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [45]:
index[1:]

Index(['b', 'c'], dtype='object')

In [46]:
#index对象是不可变的
index[1] = 'd'

TypeError: Index does not support mutable operations

In [47]:
#index不可变可在多个数据结构之间安全共享：
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [48]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [49]:
obj2.index is labels

True

In [50]:
#与python不同，pandas的Index可以包含重复的标签;
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [51]:
#5.2:基本功能
#重新索引：reindex
obj = pd.Series([4.5,7.2,-5.3,3.6],index =['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [52]:
#当某个索引值当前不存在，就引入缺失值
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [53]:
#使用前向值填充
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [54]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [55]:
#借助DataFrame,reindex可以修改（行）索引和列，只传递一个序列时，会重新索引结果的行：
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [56]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [57]:
states = ['Texas','Utah','California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [58]:
#丢弃指定轴上的项
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [60]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [61]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [63]:
#对于DataFrame，可以删除任意轴上的索引值
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [65]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [66]:
#通过传递axis = 1或axis='column'可以删除列的值：
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [70]:
data.drop(['two','four'],axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [71]:
obj.drop('c',inplace = True)
obj
#小心使用inplace，其会销毁所有被删除的数据

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [72]:
#索引、选取和过滤
#Series索引（obj[...])的工作方式类似于Numpy数组的索引，只不过Series的索引值不只是整数
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj['b']

1.0

In [74]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [76]:
obj['b':'c'] =5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [79]:
#用一个值或序列对DataFrame进行索引其实就是获取一个或多个列
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [81]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [82]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [85]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
#用 loc和iloc进行选取
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [87]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [88]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [90]:
#这两个索引函数也适用于一个标签或多个标签的切片
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [91]:
data.iloc[:,:3][data.three >5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [97]:
#使用df1的add方法，传入df2以及一个fill_value参数
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns = list('abcde'))
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [98]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [99]:
arr[0]

array([0., 1., 2., 3.])

In [100]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [5]:
#函数应用和映射
#HumPy的ufuncs（元素级数组方法）也可用于操作pandas对象
import numpy as np
frame = pd.DataFrame(np.random.randn(4,3),columns = list('bde'),index = ['Utah', 'Ohio', 'Texas',
'Oregon'])
frame

b         d         e
Utah   -1.007852 -0.504906  0.710195
Ohio   -1.354749 -1.670267  1.297381
Texas  -0.655727 -0.296075 -1.543454
Oregon  0.476233  0.677878  0.086124

In [6]:
np.abs(frame)

b         d         e
Utah    1.007852  0.504906  0.710195
Ohio    1.354749  1.670267  1.297381
Texas   0.655727  0.296075  1.543454
Oregon  0.476233  0.677878  0.086124

In [8]:
#将函数应用到由各列或行所形成的一维数组上：DataFrame的apply方法即可实现此功能：
f = lambda x: x.max() -x.min()
frame.apply(f)
#函数f,计算了一个Series的最大值和最小值的差，在frame的每列都执行了一次，结果以frame的列作为索引

b    1.830983
d    2.348145
e    2.840835
dtype: float64

In [10]:
#如果传递axis = 'columns'到apply，这个函数会在每行执行：
frame.apply(f,axis ='columns')

Utah      1.718047
Ohio      2.967647
Texas     1.247380
Oregon    0.591754
dtype: float64

In [11]:
def f(x):
    return pd.Series([x.min(),x.max()],index= ['min','max'])
frame.apply(f)

b         d         e
min -1.354749 -1.670267 -1.543454
max  0.476233  0.677878  1.297381

In [13]:
#格式化frame中各个浮点值得格式化符号，使用applymap：
format = lambda x:'%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.01  -0.50   0.71
Ohio    -1.35  -1.67   1.30
Texas   -0.66  -0.30  -1.54
Oregon   0.48   0.68   0.09

In [14]:
#Series有一个用于应用元素级函数得map方法：
frame['e'].map(format)

Utah       0.71
Ohio       1.30
Texas     -1.54
Oregon     0.09
Name: e, dtype: object

In [20]:
#排序和排名
obj = pd.Series(range(4), index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [21]:
obj.sort_index()

a    0
b    1
c    2
d    3
dtype: int64

In [22]:
#对于DataFrame,可以根据任意一个轴上的索引进行排序
frame = pd.DataFrame(np.arange(8).reshape(2,4),index = ['three','one'],columns = ['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [23]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [26]:
#数据默认是按升序排序，也可指定降序排序：
frame.sort_index(axis = 1,ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [27]:
#对Series进行排序，可使用sort_values方法：
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [28]:
#任意缺失值都默认在Series的末尾：
obj = pd.Series([4,np.nan,7,np.nan,-3,3])
obj.sort_values()

4   -3.0
5    3.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [29]:
#根据一个或多个列中的值进行排序：
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [30]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [31]:
#多列中会以第1个数
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [34]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()
#第一列的意思是第0位数7有两个，则分别为第六和第七，故取平均值：6.5;第二列代表的是-5，最小故排名第1.0

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [35]:
#也可根据值在原数据中出现的顺序给出排名：如标签0位位于标签2的前面
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [36]:
#降序
obj.rank(ascending = False,method = 'max')
#使用整个分组的最大排名，min则相反

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [37]:
obj.rank(ascending = False,method = 'min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [40]:
frame =pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [41]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [42]:
#带有重复标签的轴索引
obj = pd.Series(range(5),index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [44]:
#is_unique属性可以告诉数据是否是唯一的
obj.index.is_unique

False

In [46]:
df = pd.DataFrame(np.random.randn(4,3),index = ['a','a','b','b'])
df

0         1         2
a  0.583459  0.622647  0.709691
a  2.223895 -0.845782  0.530169
b  0.433701  0.062458  0.544883
b -0.184652 -0.224327 -0.139354

In [47]:
df.loc['b']

0         1         2
b  0.433701  0.062458  0.544883
b -0.184652 -0.224327 -0.139354

In [48]:
#汇总和计算描述统计
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [49]:
#默认含有列的和的Series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [50]:
#传入axis='columns'或axis=1将会按行进行求和运算:行用0，列用1
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [54]:
#默认NA值排除，通过skipna选项禁用该功能：
df.mean(axis = 1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [55]:
df.idxmax()

one    b
two    d
dtype: object

In [57]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [58]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [63]:
#对于非数值型数据，describe的应用：
obj = pd.DataFrame(['a','a','b','c']*4)
obj.describe()

0
count   16
unique   3
top      a
freq     8

In [66]:
#相差系数与协方差
import pandas_datareader.data as web
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] 
                      for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
for ticker, data in all_data.items()})

In [68]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-02-26  0.000574  0.001864  0.006900  0.005165
2019-02-27  0.003098 -0.003936 -0.001691  0.000825
2019-02-28 -0.009836 -0.007473 -0.001248  0.003468
2019-03-01  0.010511  0.007746  0.004463  0.018814
2019-03-04 -0.003315 -0.010488 -0.012263 -0.003646

In [69]:
#Series的corr方法用于计算两个Series中重叠的、非NA的、按索引对齐的值的相关系数
returns['MSFT'].corr(returns['IBM'])

0.4868562041044235

In [70]:
#cov用于计算协方差
returns['MSFT'].cov(returns['IBM'])

8.736984290059478e-05

In [71]:
returns.MSFT.corr(returns.IBM)

0.4868562041044235

In [72]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.372114  0.450265  0.457499
IBM   0.372114  1.000000  0.486856  0.408356
MSFT  0.450265  0.486856  1.000000  0.537518
GOOG  0.457499  0.408356  0.537518  1.000000

In [73]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000108  0.000116
IBM   0.000076  0.000153  0.000087  0.000078
MSFT  0.000108  0.000087  0.000211  0.000121
GOOG  0.000116  0.000078  0.000121  0.000238

In [74]:
returns.corrwith(returns.IBM)

AAPL    0.372114
IBM     1.000000
MSFT    0.486856
GOOG    0.408356
dtype: float64

In [75]:
returns.corrwith(volume)

AAPL   -0.059593
IBM    -0.152668
MSFT   -0.089153
GOOG   -0.017251
dtype: float64

In [76]:
#传入axis = 'columns'即可按行进行计算
#唯一值、值计算以及成员资格
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [77]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [79]:
pd.value_counts(obj.values,sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [81]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [82]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [84]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'a', 'b'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 1, 2, 2, 0, 1], dtype=int64)

In [85]:
#DataFrame中多个相关列的一张柱状图：
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],'Qu2': [2, 3, 1, 2, 3],'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [86]:
#pandas.value_counts传给该DataFrame的apply函数：
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0